version: "3"
services:
  openpanel:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CLERK_PUBLISHABLE_KEY=your_key_here
      - CLERK_SECRET_KEY=your_key_here
      - CLERK_WEBHOOK_SECRET=your_webhook_secret_here
