version: "3.8"

services:
  app:
    image: ghcr.io/openpanel-dev/openpanel:latest
    environment:
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
      - DATABASE_URL=clickhouse://default:password@clickhouse:8123/openpanel
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openpanel.rule=Host(`analytics.joncoronel.com`)"
      - "traefik.http.services.openpanel.loadbalancer.server.port=3000"
    depends_on:
      - clickhouse
      - redis

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    environment:
      - CLICKHOUSE_DB=openpanel
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  redis:
    image: redis:7-alpine
    command: redis-server --notify-keyspace-events Ex
    volumes:
      - redis_data:/data

volumes:
  clickhouse_data:
  redis_data:
