version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    environment:
      - CLICKHOUSE_DB=openpanel
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    command: redis-server --notify-keyspace-events Ex
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PASSWORD=password
      - REDIS_HOST=redis
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openpanel.rule=Host(`analytics.joncoronel.com`)"
      - "traefik.http.services.openpanel.loadbalancer.server.port=3000"
    depends_on:
      - clickhouse
      - redis

volumes:
  clickhouse_data:
  redis_data:
